"""Paired NHANES survey-cluster bootstrap of the fixed-eta/beta SR anchor.

The same rescaled PSU weights are regenerated by bootstrap_groups.py, so
overlapping groups and their full-cohort anchor use identical resamples.
"""
from __future__ import annotations

import argparse
import json
import os
import time
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.optimize import brentq, minimize

from refit_fixed_eta_beta import DelayedEntryLikelihood, MEX_MAX

HERE = Path(__file__).resolve().parent
POINT = json.loads((HERE / "inputs" / "best_constrained_fit.json").read_text())["params"]
SEED = 20260924


def resampled_frame(rep: int) -> pd.DataFrame:
    if rep < 1:
        raise ValueError("Bootstrap replicate must be positive")
    frame = pd.read_csv(HERE / "inputs" / "nhanes.csv")
    weights = np.zeros(len(frame), dtype=float)
    rng = np.random.default_rng(np.random.SeedSequence([SEED, rep, 1]))
    for _, block in frame.groupby(["wave", "SDMVSTRA"], sort=True):
        psus = np.sort(block.SDMVPSU.unique())
        n = len(psus)
        if n < 2:
            raise ValueError("NHANES stratum has fewer than two PSUs")
        counts = np.bincount(rng.choice(n, n - 1, replace=True), minlength=n)
        for psu, count in zip(psus, counts):
            weights[block.index[block.SDMVPSU == psu]] = n * count / (n - 1)
    frame["bootstrap_weight"] = weights
    return frame


class WeightedLikelihood(DelayedEntryLikelihood):
    def __init__(self, data: pd.DataFrame, n: int, dt: float, quadrature: int):
        super().__init__(data, n, dt, quadrature)
        self.weight = data.bootstrap_weight.to_numpy(float)
        self.event_weight = self.weight[self.event == 1]
        self.followup = float(np.sum(self.weight * (self.exit - self.entry)))

    def profile_mex(self, xc: float, epsilon: float, cv: float):
        log_s, hazard = self.curve(float(xc), float(epsilon), float(cv))
        survival_term = (np.interp(self.exit, self.grid, log_s)
                         - np.interp(self.entry, self.grid, log_s))
        event_hazard = np.interp(self.event_exit, self.midpoints, hazard)

        def derivative(m: float) -> float:
            return self.followup - np.sum(
                self.event_weight / np.maximum(event_hazard + m, 1e-250))

        if derivative(0.0) >= 0:
            mex = 0.0
        elif derivative(MEX_MAX) <= 0:
            mex = MEX_MAX
        else:
            mex = float(brentq(derivative, 0.0, MEX_MAX, xtol=1e-12))
        nll = (-np.sum(self.weight * survival_term) + mex * self.followup
               - np.sum(self.event_weight * np.log(
                   np.maximum(event_hazard + mex, 1e-250))))
        return float(nll), float(mex)


def fit_one(rep: int) -> None:
    out = HERE / "bootstrap" / "baseline" / f"rep_{rep:03d}.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    if out.exists():
        print("EXISTS", out, flush=True)
        return
    data = resampled_frame(rep)
    like = WeightedLikelihood(data, 160, 0.05, 21)
    starts = [
        (POINT["Xc"], POINT["epsilon"], POINT["CV"]),
        (POINT["Xc"] * 0.8, POINT["epsilon"] * 1.2, min(0.49, POINT["CV"] * 1.2)),
    ]
    traces = []
    started = time.monotonic()
    bounds = [(np.log(0.02), np.log(3000.0)),
              (np.log(0.002), np.log(20_000_000.0)), (0.0, 0.5)]
    for xc, epsilon, cv in starts:
        q0 = np.array([np.log(xc), np.log(epsilon), cv])

        def objective(q):
            return like.profile_mex(float(np.exp(q[0])), float(np.exp(q[1])),
                                    float(q[2]))[0]

        result = minimize(objective, q0, method="L-BFGS-B", jac="3-point",
                          bounds=bounds, options={"maxiter": 180, "ftol": 1e-9,
                                                   "gtol": 0.002, "maxls": 30,
                                                   "finite_diff_rel_step": 2e-5})
        x, e, c = float(np.exp(result.x[0])), float(np.exp(result.x[1])), float(result.x[2])
        nll, mex = like.profile_mex(x, e, c)
        traces.append({"Xc": x, "epsilon": e, "CV": c, "mex": mex,
                       "nll": nll, "success": bool(result.success),
                       "message": str(result.message), "nfev": int(result.nfev)})
    best = min(traces, key=lambda r: r["nll"])
    checker = WeightedLikelihood(data, 320, 0.025, 31)
    check_nll, check_mex = checker.profile_mex(best["Xc"], best["epsilon"], best["CV"])
    payload = {"replicate": rep, "seed": SEED,
               "method": "Rao-Wu n-1 PSU bootstrap within wave and stratum",
               "params": {"eta": POINT["eta"], "beta": POINT["beta"],
                          "kappa": POINT["kappa"], "Xc": best["Xc"],
                          "epsilon": best["epsilon"], "CV": best["CV"],
                          "mex": check_mex},
               "fit_nll": best["nll"], "check_nll": check_nll,
               "success": bool(best["success"]), "traces": traces,
               "weighted_n": float(data.bootstrap_weight.sum()),
               "weighted_deaths": float(np.sum(data.bootstrap_weight * data.event)),
               "seconds": time.monotonic() - started}
    tmp = out.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(payload, indent=2, allow_nan=False))
    tmp.replace(out)
    print("BASELINE", rep, check_nll, payload["success"], flush=True)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--rep", type=int, default=int(os.environ.get("LSB_JOBINDEX", "1")))
    args = parser.parse_args()
    fit_one(args.rep)
